Update CHANGELOG.md
opendevstack/ods-configuration-sample pull request #11
Opened 2018-08-21 14:41 UTC by clemensutschig

2018-08-22 03:28 UTC, michaelsauter requested changes

2018-08-22 03:28 UTC, michaelsauter commented on CHANGELOG.md
> +## 0.2.0RC *current master*
Typically, you'd record changes in a changelog in reverse order, so latest release is on top. 

Also, any changes on current master that have not been released yet, are located under the `Unreleased` headline.

These recommendations are based on https://keepachangelog.com/en/1.0.0/, which is quite common ...

2018-08-22 08:43 UTC, clemensutschig commented
@michaelsauter  - please check again ... cool?

2018-08-24 02:50 UTC, michaelsauter approved these changes

2018-08-24 05:31 UTC, merged